export { default as Navbar } from './Navbar'
export { default as Header } from './Header'
export { default as About } from './About'
export { default as Process } from './Process'
export { default as Legacy } from './Legacy'
export { default as Contact } from './Contact'